
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"                 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init.sql

  orders-service:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "8081:8081"
    environment:
      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin123
      # Base de datos para pedidos
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pedidos_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - rabbitmq
      - mysql

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin123
      # Base de datos para inventario
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - rabbitmq
      - mysql

volumes:
  mysql_data:
